'''
Created on 21.05.2014

@author: Q350609
'''

"""
    this abstract data structure for parameters of Simulator Test
    its instance is generated by converting from JSON or other formats
"""

class SimulatorTest():

    def __init__(self, tst_item):  #test_iten may be the item in dictionary, which is converted from JSON file
        self._tst = tst_item

    @classmethod
    def __init_tstplan__(cls, items_list):
        tsts_list = []
        for item in items_list:
            tsts_list.append(cls(item))
        return tsts_list


    @classmethod
    def __init_model_name_set__(cls, items_list):
        name_list = set()
        for item in items_list:
            name_list.add(cls(item).model_name)
        return set(name_list)


    @property
    def tst_name(self):
        pass

    @property
    def model_name(self):
        pass

    @property
    def simulation_settings(self):
        pass

    @property
    def parameters(self):
        pass

    @property
    def results(self):
        pass

